name: primary
container:
  port: 5432
  name: primary
credentials:
  primary: password
  root: password
  user: password
serviceType: ClusterIP
image:
  repository: crunchydata
  container: crunchy-postgres
  tag: centos7-10.3-1.8.2
resources:
  cpu: 200m
  memory: 512Mi
